apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-app
        image: 244170403840.dkr.ecr.us-west-1.amazonaws.com/my-app:ff3642edc982013685f726a3e022d1975c7ca5e5
        ports:
        - containerPort: 3000
