apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-app
        image: 244170403840.dkr.ecr.us-west-1.amazonaws.com/my-app:60bca796145ee525b3ab402f92e6ef86afa9ee7f
        ports:
        - containerPort: 80
